export const wilayas = [
    { code: '01', name_fr: 'Adrar', name_ar: 'أدرار', home_fee: 900, stopdesk_fee: 500 },
    { code: '02', name_fr: 'Chlef', name_ar: 'الشلف', home_fee: 700, stopdesk_fee: 400 },
    { code: '03', name_fr: 'Laghouat', name_ar: 'الأغواط', home_fee: 800, stopdesk_fee: 450 },
    { code: '04', name_fr: 'Oum El Bouaghi', name_ar: 'أم البواقي', home_fee: 700, stopdesk_fee: 400 },
    { code: '05', name_fr: 'Batna', name_ar: 'باتنة', home_fee: 700, stopdesk_fee: 400 },
    { code: '06', name_fr: 'Béjaïa', name_ar: 'بجاية', home_fee: 700, stopdesk_fee: 400 },
    { code: '07', name_fr: 'Biskra', name_ar: 'بسكرة', home_fee: 800, stopdesk_fee: 450 },
    { code: '08', name_fr: 'Béchar', name_ar: 'بشار', home_fee: 900, stopdesk_fee: 500 },
    { code: '09', name_fr: 'Blida', name_ar: 'البليدة', home_fee: 500, stopdesk_fee: 250 },
    { code: '10', name_fr: 'Bouira', name_ar: 'البويرة', home_fee: 600, stopdesk_fee: 300 },
    { code: '11', name_fr: 'Tamanrasset', name_ar: 'تمنراست', home_fee: 1200, stopdesk_fee: 800 },
    { code: '12', name_fr: 'Tébessa', name_ar: 'تبسة', home_fee: 800, stopdesk_fee: 450 },
    { code: '13', name_fr: 'Tlemcen', name_ar: 'تلمسان', home_fee: 700, stopdesk_fee: 400 },
    { code: '14', name_fr: 'Tiaret', name_ar: 'تيارت', home_fee: 700, stopdesk_fee: 400 },
    { code: '15', name_fr: 'Tizi Ouzou', name_ar: 'تيزي وزو', home_fee: 600, stopdesk_fee: 300 },
    { code: '16', name_fr: 'Alger', name_ar: 'الجزائر', home_fee: 400, stopdesk_fee: 200 },
    { code: '17', name_fr: 'Djelfa', name_ar: 'الجلفة', home_fee: 800, stopdesk_fee: 450 },
    { code: '18', name_fr: 'Jijel', name_ar: 'جيجل', home_fee: 700, stopdesk_fee: 400 },
    { code: '19', name_fr: 'Sétif', name_ar: 'سطيف', home_fee: 600, stopdesk_fee: 300 },
    { code: '20', name_fr: 'Saïda', name_ar: 'سعيدة', home_fee: 700, stopdesk_fee: 400 },
    { code: '21', name_fr: 'Skikda', name_ar: 'سكيكدة', home_fee: 700, stopdesk_fee: 400 },
    { code: '22', name_fr: 'Sidi Bel Abbès', name_ar: 'سيدي بلعباس', home_fee: 700, stopdesk_fee: 400 },
    { code: '23', name_fr: 'Annaba', name_ar: 'عنابة', home_fee: 600, stopdesk_fee: 300 },
    { code: '24', name_fr: 'Guelma', name_ar: 'قالمة', home_fee: 700, stopdesk_fee: 400 },
    { code: '25', name_fr: 'Constantine', name_ar: 'قسنطينة', home_fee: 600, stopdesk_fee: 300 },
    { code: '26', name_fr: 'Médéa', name_ar: 'المدية', home_fee: 600, stopdesk_fee: 300 },
    { code: '27', name_fr: 'Mostaganem', name_ar: 'مستغانم', home_fee: 700, stopdesk_fee: 400 },
    { code: '28', name_fr: 'M\'Sila', name_ar: 'المسيلة', home_fee: 700, stopdesk_fee: 400 },
    { code: '29', name_fr: 'Mascara', name_ar: 'معسكر', home_fee: 700, stopdesk_fee: 400 },
    { code: '30', name_fr: 'Ouargla', name_ar: 'ورقلة', home_fee: 900, stopdesk_fee: 500 },
    { code: '31', name_fr: 'Oran', name_ar: 'وهران', home_fee: 600, stopdesk_fee: 300 },
    // ... can add more later
];
