export const wilayas = [
    { code: '01', name_fr: 'Adrar', name_ar: 'أدرار', home_fee: 900, stopdesk_fee: 500 },
    { code: '02', name_fr: 'Chlef', name_ar: 'الشلف', home_fee: 700, stopdesk_fee: 400 },
    { code: '03', name_fr: 'Laghouat', name_ar: 'الأغواط', home_fee: 800, stopdesk_fee: 450 },
    { code: '04', name_fr: 'Oum El Bouaghi', name_ar: 'أم البواقي', home_fee: 700, stopdesk_fee: 400 },
    { code: '05', name_fr: 'Batna', name_ar: 'باتنة', home_fee: 700, stopdesk_fee: 400 },
    { code: '06', name_fr: 'Béjaïa', name_ar: 'بجاية', home_fee: 700, stopdesk_fee: 400 },
    { code: '07', name_fr: 'Biskra', name_ar: 'بسكرة', home_fee: 800, stopdesk_fee: 450 },
    { code: '08', name_fr: 'Béchar', name_ar: 'بشار', home_fee: 900, stopdesk_fee: 500 },
    { code: '09', name_fr: 'Blida', name_ar: 'البليدة', home_fee: 500, stopdesk_fee: 250 },
    { code: '10', name_fr: 'Bouira', name_ar: 'البويرة', home_fee: 600, stopdesk_fee: 300 },
    { code: '11', name_fr: 'Tamanrasset', name_ar: 'تمنراست', home_fee: 1200, stopdesk_fee: 800 },
    { code: '12', name_fr: 'Tébessa', name_ar: 'تبسة', home_fee: 800, stopdesk_fee: 450 },
    { code: '13', name_fr: 'Tlemcen', name_ar: 'تلمسان', home_fee: 700, stopdesk_fee: 400 },
    { code: '14', name_fr: 'Tiaret', name_ar: 'تيارت', home_fee: 700, stopdesk_fee: 400 },
    { code: '15', name_fr: 'Tizi Ouzou', name_ar: 'تيزي وزو', home_fee: 600, stopdesk_fee: 300 },
    { code: '16', name_fr: 'Alger', name_ar: 'الجزائر', home_fee: 400, stopdesk_fee: 200 },
    { code: '17', name_fr: 'Djelfa', name_ar: 'الجلفة', home_fee: 800, stopdesk_fee: 450 },
    { code: '18', name_fr: 'Jijel', name_ar: 'جيجل', home_fee: 700, stopdesk_fee: 400 },
    { code: '19', name_fr: 'Sétif', name_ar: 'سطيف', home_fee: 600, stopdesk_fee: 300 },
    { code: '20', name_fr: 'Saïda', name_ar: 'سعيدة', home_fee: 700, stopdesk_fee: 400 },
    { code: '21', name_fr: 'Skikda', name_ar: 'سكيكدة', home_fee: 700, stopdesk_fee: 400 },
    { code: '22', name_fr: 'Sidi Bel Abbès', name_ar: 'سيدي بلعباس', home_fee: 700, stopdesk_fee: 400 },
    { code: '23', name_fr: 'Annaba', name_ar: 'عنابة', home_fee: 600, stopdesk_fee: 300 },
    { code: '24', name_fr: 'Guelma', name_ar: 'قالمة', home_fee: 700, stopdesk_fee: 400 },
    { code: '25', name_fr: 'Constantine', name_ar: 'قسنطينة', home_fee: 600, stopdesk_fee: 300 },
    { code: '26', name_fr: 'Médéa', name_ar: 'المدية', home_fee: 600, stopdesk_fee: 300 },
    { code: '27', name_fr: 'Mostaganem', name_ar: 'مستغانم', home_fee: 700, stopdesk_fee: 400 },
    { code: '28', name_fr: 'M\'Sila', name_ar: 'المسيلة', home_fee: 700, stopdesk_fee: 400 },
    { code: '29', name_fr: 'Mascara', name_ar: 'معسكر', home_fee: 700, stopdesk_fee: 400 },
    { code: '30', name_fr: 'Ouargla', name_ar: 'ورقلة', home_fee: 900, stopdesk_fee: 500 },
    { code: '31', name_fr: 'Oran', name_ar: 'وهران', home_fee: 600, stopdesk_fee: 300 },
    { code: '32', name_fr: 'El Bayadh', name_ar: 'البيض', home_fee: 800, stopdesk_fee: 450 },
    { code: '33', name_fr: 'Illizi', name_ar: 'إليزي', home_fee: 1200, stopdesk_fee: 800 },
    { code: '34', name_fr: 'Bordj Bou Arreridj', name_ar: 'برج بوعريريج', home_fee: 700, stopdesk_fee: 400 },
    { code: '35', name_fr: 'Boumerdès', name_ar: 'بومرداس', home_fee: 600, stopdesk_fee: 300 },
    { code: '36', name_fr: 'El Tarf', name_ar: 'الطارف', home_fee: 700, stopdesk_fee: 400 },
    { code: '37', name_fr: 'Tindouf', name_ar: 'تندوف', home_fee: 1200, stopdesk_fee: 800 },
    { code: '38', name_fr: 'Tissemsilt', name_ar: 'تيسمسيلت', home_fee: 700, stopdesk_fee: 400 },
    { code: '39', name_fr: 'El Oued', name_ar: 'الوادي', home_fee: 900, stopdesk_fee: 500 },
    { code: '40', name_fr: 'Khenchela', name_ar: 'خنشلة', home_fee: 700, stopdesk_fee: 400 },
    { code: '41', name_fr: 'Souk Ahras', name_ar: 'سوق أهراس', home_fee: 700, stopdesk_fee: 400 },
    { code: '42', name_fr: 'Tipaza', name_ar: 'تيبازة', home_fee: 600, stopdesk_fee: 300 },
    { code: '43', name_fr: 'Mila', name_ar: 'ميلة', home_fee: 700, stopdesk_fee: 400 },
    { code: '44', name_fr: 'Aïn Defla', name_ar: 'عين الدفلى', home_fee: 700, stopdesk_fee: 400 },
    { code: '45', name_fr: 'Naâma', name_ar: 'النعامة', home_fee: 800, stopdesk_fee: 450 },
    { code: '46', name_fr: 'Aïn Témouchent', name_ar: 'عين تموشنت', home_fee: 700, stopdesk_fee: 400 },
    { code: '47', name_fr: 'Ghardaïa', name_ar: 'غرداية', home_fee: 900, stopdesk_fee: 500 },
    { code: '48', name_fr: 'Relizane', name_ar: 'غليزان', home_fee: 700, stopdesk_fee: 400 },
    { code: '49', name_fr: 'Timimoun', name_ar: 'تيميمون', home_fee: 1000, stopdesk_fee: 600 },
    { code: '50', name_fr: 'Bordj Badji Mokhtar', name_ar: 'برج باجي مختار', home_fee: 1200, stopdesk_fee: 800 },
    { code: '51', name_fr: 'Ouled Djellal', name_ar: 'أولاد جلال', home_fee: 900, stopdesk_fee: 500 },
    { code: '52', name_fr: 'Béni Abbès', name_ar: 'بني عباس', home_fee: 1000, stopdesk_fee: 600 },
    { code: '53', name_fr: 'In Salah', name_ar: 'عين صالح', home_fee: 1000, stopdesk_fee: 600 },
    { code: '54', name_fr: 'In Guezzam', name_ar: 'عين قزام', home_fee: 1200, stopdesk_fee: 800 },
    { code: '55', name_fr: 'Touggourt', name_ar: 'تقرت', home_fee: 900, stopdesk_fee: 500 },
    { code: '56', name_fr: 'Djanet', name_ar: 'جانت', home_fee: 1200, stopdesk_fee: 800 },
    { code: '57', name_fr: 'El M\'Ghair', name_ar: 'المغير', home_fee: 900, stopdesk_fee: 500 },
    { code: '58', name_fr: 'El Meniaa', name_ar: 'المنيعة', home_fee: 900, stopdesk_fee: 500 },
    { code: '59', name_fr: 'Barika', name_ar: 'بريكة', home_fee: 700, stopdesk_fee: 400 },
    { code: '60', name_fr: 'Aflou', name_ar: 'أفلو', home_fee: 800, stopdesk_fee: 450 },
    { code: '61', name_fr: 'El Abiodh Sidi Cheikh', name_ar: 'الأبيض سيدي الشيخ', home_fee: 800, stopdesk_fee: 450 },
    { code: '62', name_fr: 'Ksar Chellala', name_ar: 'قصر الشلالة', home_fee: 700, stopdesk_fee: 400 },
    { code: '63', name_fr: 'Boussaâda', name_ar: 'بوسعادة', home_fee: 700, stopdesk_fee: 400 },
    { code: '64', name_fr: 'Messaâd', name_ar: 'مسعد', home_fee: 800, stopdesk_fee: 450 },
    { code: '65', name_fr: 'Aïn Oussera', name_ar: 'عين وسارة', home_fee: 800, stopdesk_fee: 450 },
    { code: '66', name_fr: 'Bir El Ater', name_ar: 'بئر العاتر', home_fee: 800, stopdesk_fee: 450 },
    { code: '67', name_fr: 'El Kantara', name_ar: 'القنطرة', home_fee: 800, stopdesk_fee: 450 },
    { code: '68', name_fr: 'Ksar El Boukhari', name_ar: 'قصر البخاري', home_fee: 600, stopdesk_fee: 300 },
    { code: '69', name_fr: 'El Aricha', name_ar: 'العريشة', home_fee: 700, stopdesk_fee: 400 },
];
